### ISSUE TITLE
[Bug]: `tooth name mismatch` because of a typo

### ISSUE THREAD

**Issue by Wesley-Young** [engsr6982/LeviTPSystem#2]
### Describe the bug

Error occurred when installing via `lip` as follows:
```
Jul 17 14:48:24.769 [INFO] Downloading teeth and resolving dependencies...
Jul 17 14:48:24.776 [ERRO]
        failed to parse and download specifier string list
        failed to download specifier github.com/engsr6982/LeviTPSystem@0.1.0
        failed to download archive of github.com/engsr6982/LeviTPSystem@0.1.0
        failed to validate archive
        tooth name mismatch: githbu.com/engsr6982/LeviTPSystem != github.com/engsr6982/LeviTPSystem
```

Clearly here a typo (`github` -> `githbu`) occurred.

### To Reproduce

Run `lip install github.com/engsr6982/LeviTPSystem@0.1.0` via shell

### Expected behavior

The plugin should be correctly installed.

**Comment by engsr6982** [comment]
fixed
https://github.com/engsr6982/LeviTPSystem/releases/tag/v0.2.0
