### ISSUE TITLE
[Bug]: 加载优先级报错无法加载PermissionCore

### ISSUE THREAD

**Issue by Blackhaihai** [engsr6982/LeviTPSystem#3]
### Describe the bug

在这个程序加载时我这里报错 
缺少模块：
01:52:13.650 ERROR [LeviLamina]    |- PermissionCore.dll
可是在下方调用的前置模块才进行加载导致报错无法使用
01:52:13.712 INFO [LeviLamina] PermissionCore 已加载

### To Reproduce

[LeviLamina]版本"0.13.4"，
LeviTPSystem版本 "0.2.1",
PermissionCore版本"0.10.1",

### Expected behavior

希望修复

### Screenshots

![屏幕截图 2024-07-27 015639](https://github.com/user-attachments/assets/728a16ac-08bf-4ad8-9d23-1c331431ec83)

### Platform

windows 11

### BDS Version

1.21.2

### LeviLamina Version

0.13.4

### Version

0.2.1

**Comment by engsr6982** [comment]
fixed https://github.com/engsr6982/LeviTPSystem/releases/tag/v0.2.2
