### ISSUE TITLE
希望增加某一权限组的home传送点数量能无视最大家园的数量限制

### ISSUE THREAD

**Issue by xuantianzhilin** [engsr6982/LeviTPSystem#5]
### Is your feature request related to a problem? Please describe.

在服务器的建设中管理员可能需要多个传送点，这个数量的需求可能超过服务器给正常玩家设置的数量上线。

### Describe the solution you'd like

希望增加某一权限组的home传送点数量能无视最大家园的数量限制

**Comment by engsr6982** [comment]
已支持 https://github.com/engsr6982/LeviTPSystem/releases/tag/v0.3.0
